apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-nfs-claim
  namespace: hlc-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
