apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-nfs-claim
  namespace: hlc-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlc-server
  namespace: hlc-storage
  labels:
    kubernetes.io/cluster-service: "true"

spec:
  replicas: 4
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
        kubernetes.io/cluster-service: "true"

    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: nfs-storage
          mountPath: /nfs
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: cephfs-nfs-claim
            readOnly: false

